version: 3

final_space: true

blocks:
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        style: plain
        template: "\u256d\u2500"
        background: transparent
        foreground: 21c7c7
        foreground_templates:
          - '{{ if gt .Code 0 }}#c9605f{{ end }}'
      - type: path
        style: plain
        template: " {{ .Path }}"
        background: transparent
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        style: plain
        template: "\u2570\u2500"
        foreground: 21c7c7
        foreground_templates:
          - '{{ if gt .Code 0 }}#c9605f{{ end }}'
      - type: status
        style: plain
        template: " "
        foreground: e0f8ff
        foreground_templates:
          - '{{ if gt .Code 0 }}#c9605f{{ end }}'
        properties:
          always_enabled: true

transient_prompt:
  backgrond: transparent
  template: "  "
